CREATE TABLE IF NOT EXISTS mate_provider_account (
    id BIGINT NOT NULL,
    provider_id VARCHAR(128) NOT NULL,
    label VARCHAR(160) NOT NULL,
    external_account_id VARCHAR(256) NULL,
    auth_type VARCHAR(32) NOT NULL DEFAULT 'api_key',
    credential_json TEXT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    priority INT NOT NULL DEFAULT 100,
    status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    quota_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    quota_used_percent DECIMAL(5,2) NULL,
    quota_reset_at BIGINT NULL,
    quota_updated_at BIGINT NULL,
    alert_enabled TINYINT(1) NOT NULL DEFAULT 1,
    alert_threshold_percent DECIMAL(5,2) NOT NULL DEFAULT 80.00,
    alert_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    last_error_code VARCHAR(128) NULL,
    last_error_message TEXT NULL,
    last_success_at BIGINT NULL,
    last_failure_at BIGINT NULL,
    last_used_at BIGINT NULL,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    legacy_import TINYINT(1) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_provider_account_pool (provider_id, enabled, priority),
    UNIQUE KEY uk_provider_account_external (provider_id, external_account_id),
    UNIQUE KEY uk_provider_account_legacy (provider_id, legacy_import),
    CONSTRAINT fk_provider_account_provider FOREIGN KEY (provider_id)
        REFERENCES mate_model_provider(provider_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
